### PR TITLE
dialog box

### PR DESCRIPTION
**Pull request by antoineherzog**

### CODE REVIEW

**Comment by antoineherzog** [comment]
@davepuchyr Yes my idea was to make it super visible in a next PR. So we can push in staging then production so we can test the flow with real user then display it after a login. let me know what do you think ..

**Comment by davepuchyr** [comment]
> @davepuchyr Yes my idea was to make it super visible in a next PR. So we can push in staging then production so we can test the flow with real user then display it after a login. let me know what do you think ..

Ah, ok, I didn't know you had another PR in mind.  Sounds good.  I still think that the star1 address should not be removable, though.

**Comment by antoineherzog** [comment]
i don't know how to do that .. I propose to merge this one, I can do another one about not revmoing starname address in another PR is it i good for you ? @davepuchyr

**Comment by davepuchyr** [comment]
> i don't know how to do that .. I propose to merge this one, I can do another one about not revmoing starname address in another PR is it i good for you ? @davepuchyr

OK

**Pull request merged**
