### PR TITLE
Adding cosmos into extension

### PR DESCRIPTION
**Pull request by antoineherzog**

### CODE REVIEW

**Comment by albertandrejev** [comment]
Please do not merge it until `https://github.com/iov-one/ponferrada/tree/milestone/account-module-support` will be merged into master. Then rebase this PR with master and merge. Unfortunately changes in `https://github.com/iov-one/ponferrada/tree/milestone/account-module-support` was required to implement this PR.

**Comment by albertandrejev** [comment]
@webmaster128 can you review this PR too please,your Medium article (https://medium.com/confio/adding-cosmwasm-to-the-neuma-multichain-wallet-ec657d893268) was used to add `cosmwasm-js` support, but I am not sure about proper staging and production configuration. Thank you!

**Comment by albertandrejev** [comment]
Unfortunately I do not know how to test ATOM (I need it to close https://github.com/iov-one/ponferrada/issues/999), it was added to the configuration, but how can I tests it? I tried with another available token from cosmos bank tokens, everything works fine. 
- [ ] Display COSM balance in the Wallet - displaying ATOM
- [ ] send COSM in the Wallet
- [ ] extension + iov core?

**Comment by webmaster128** [comment]
👋 What's the goal of this PR?

CosmWasm is a module for Cosmos SDK, not a blockchain. Everthing you find in @cosmwasm/sdk is targeting Cosmos SDK 0.38. Cosmos Hub runs a significatly older version of Cosmos SDK. So @cosmwasm/sdk is not supporting and does not try to support ATOMs.

**Comment by albertandrejev** [comment]
@antoineherzog :arrow_up:

**Comment by albertandrejev** [comment]
@webmaster128 but it was used in exact same way like was described in your article, nothing more.

**Comment by webmaster128** [comment]
> but it was used in exact same way like was described in your article, nothing more.

What I wrote in the article did not claim to be compatible to Cosmos Hub / ATOM.

**Pull request closed without merging**
